name: qds_common_widget
description: "wippy designsystem component common widget"
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/component/common_widget
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  qds_foundation: ^0.0.1
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.10.0
  qds_spinner: ^0.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
