name: quantum_dots
description: the design system for wippy global product
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/quantum_dots
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qds_foundation: ^0.0.1
  qds_button: ^0.0.1
  qds_input: ^0.0.1
  qds_toast: ^0.0.1
  qds_markdown_text: ^0.0.1
  qds_progress: ^0.0.1
  qds_spinner: ^0.0.1
  qds_header: ^0.0.1
  qds_common_widget: ^0.0.1
  qds_bottom_sheet: ^0.0.1
  qds_badge: ^0.0.1
  qds_chips: ^0.0.1
  qds_popup: ^0.0.1
  qds_empty_states: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
