name: qds_toast
description: "wippy designsystem component toast"
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/component/toast
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  qds_foundation: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  mockito: ^5.4.4
  bloc_test: ^9.1.7
