name: qds_markdown_text
description: "wippy designsystem component markdown_text"
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/component/markdown_text
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qds_foundation: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
