name: qds_foundation
description: "wippy design system foundation"
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/foundation
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
