name: qds_header
description: "wippy designsystem component header"
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots/component/header
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  qds_foundation: ^0.0.1
  qds_common_widget: ^0.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  mockito: ^5.4.4
