name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest-2x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Pub get
        run: melos exec -- flutter pub get

      - name: Run analyze
        run: melos run analyze

      - name: Install Codev
        run: dart pub global activate coverde

      - name: Run tests
        run: melos run unit_test
