name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - name: Extract version from pubspec.yaml
        id: get-version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | awk '{print $2}' | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ env.version }}
          name: v${{ env.version }}
          publish: true